apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: markdown-render
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /markdown
        backend:
          serviceName: markdown-render
          servicePort: http
