apiVersion: v1
kind: Service
metadata:
  name: markdown-render
  labels:
    app: markdown-render
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: markdown-render
